[package]
name = "tsp_2opt"
version = "0.1.0"
authors = ["mehdi <mehdi-bs@live.fr>"]
edition = "2018"

[lib]
name = "tsp_2opt"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[package.metadata.maturin]
requires-dist = ["numpy=1.20.1"]
