[package]
name = "pyext-2opt"
version = "0.1.0"
authors = ["mehdi"]
edition = "2018"

[lib]
name = "2opt"
crate-type = ["dylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

